### ISSUE TITLE
assets precompile not found in production mode

### ISSUE THREAD

**Issue by FedeG** [lelylan/people#40]
If run this command: `rake assets:precompile RAILS_ENV=production --trace` return error.

#### Log:
```bash
root@dd5f155cefd5:/usr/src/app# rake assets:precompile RAILS_ENV=production --trace
** Invoke assets:precompile (first_time)
** Execute assets:precompile
/usr/bin/ruby1.9.1 /usr/local/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets --trace
** Invoke assets:precompile:all (first_time)
** Execute assets:precompile:all
** Invoke assets:precompile:primary (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
AssetSync: using default configuration from built-in initializer
** Invoke tmp:cache:clear (first_time)
** Execute tmp:cache:clear
** Execute assets:precompile:primary
Compiled jquery.js  (2ms)  (pid 35)
Compiled jquery_ujs.js  (0ms)  (pid 35)
Compiled jquery.shorten.js  (0ms)  (pid 35)
Compiled application.js  (43ms)  (pid 35)
Compiled bootstrap.min.css  (0ms)  (pid 35)
Compiled default.css  (0ms)  (pid 35)
Compiled application.css  (25ms)  (pid 35)
Compiled doorkeeper/application.js  (3ms)  (pid 35)
Compiled doorkeeper/bootstrap.min.css  (1ms)  (pid 35)
Compiled doorkeeper/form.css  (0ms)  (pid 35)
Compiled doorkeeper/application.css  (317ms)  (pid 35)
** Invoke assets:precompile:nondigest (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
AssetSync: using default configuration from built-in initializer
** Invoke tmp:cache:clear (first_time)
** Execute tmp:cache:clear
** Execute assets:precompile:nondigest
Compiled jquery.js  (1ms)  (pid 35)
Compiled jquery_ujs.js  (0ms)  (pid 35)
Compiled jquery.shorten.js  (0ms)  (pid 35)
Compiled application.js  (14ms)  (pid 35)
Compiled bootstrap.min.css  (0ms)  (pid 35)
Compiled default.css  (0ms)  (pid 35)
Compiled application.css  (6ms)  (pid 35)
Compiled doorkeeper/application.js  (0ms)  (pid 35)
Compiled doorkeeper/bootstrap.min.css  (0ms)  (pid 35)
Compiled doorkeeper/form.css  (0ms)  (pid 35)
Compiled doorkeeper/application.css  (6ms)  (pid 35)
rake aborted!
Fog provider can't be blank, Fog directory can't be blank
/var/lib/gems/1.9.1/gems/asset_sync-0.5.4/lib/asset_sync/asset_sync.rb:32:in `sync'
/var/lib/gems/1.9.1/gems/asset_sync-0.5.4/lib/tasks/asset_sync.rake:3:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/var/lib/gems/1.9.1/gems/rake-10.0.4/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => assets:precompile:nondigest
rake aborted!
Command failed with status (1): [/usr/bin/ruby1.9.1 /usr/local/bin/rake ass...]
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `call'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `sh'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/file_utils_ext.rb:37:in `sh'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/file_utils.rb:80:in `ruby'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/file_utils_ext.rb:37:in `ruby'
/var/lib/gems/1.9.1/gems/actionpack-3.2.13/lib/sprockets/assets.rake:12:in `ruby_rake_task'
/var/lib/gems/1.9.1/gems/actionpack-3.2.13/lib/sprockets/assets.rake:21:in `invoke_or_reboot_rake_task'
/var/lib/gems/1.9.1/gems/actionpack-3.2.13/lib/sprockets/assets.rake:29:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/var/lib/gems/1.9.1/gems/rake-10.0.4/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => assets:precompile
```

#### Environment variables:
```bash
root@55c96fd38e72:/usr/src/app# export
declare -x HOME="/root"
declare -x HOSTNAME="55c96fd38e72"
declare -x LELYLAN_DEVICES_URL="devices"
declare -x LELYLAN_PEOPLE_URL="people"
declare -x LELYLAN_PROFILES_URL="profiles"
declare -x LELYLAN_SUBSCRIPTIONS_URL="subscriptions"
declare -x LELYLAN_TYPES_URL="types"
declare -x MEMCACHIER_PASSWORD="password"
declare -x MEMCACHIER_SERVERS="memcached:11211"
declare -x MEMCACHIER_USERNAME="user"
declare -x MONGOLAB_DEVICES_URL="mongodb://mongodb:27017/devices"
declare -x MONGOLAB_JOBS_URL="mongodb://mongodb:27017/jobs"
declare -x MONGOLAB_LOCATIONS_URL="mongodb://mongodb:27017/"
declare -x MONGOLAB_PEOPLE_URL="mongodb://mongodb:27017/people"
declare -x MONGOLAB_SUBSCRIPTIONS_URL/
declare -x MONGOLAB_TYPES_URL="mongodb://mongodb:27017/types"
declare -x NODE_ENV="production"
declare -x NODE_VERSION="0.10.46"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PORT="80"
declare -x PWD="/usr/src/app"
declare -x RACK_ENV="production"
declare -x RAILS_ENV="production"
declare -x REDIS_RATE_LIMIT_URL="redis://redis:6379/"
declare -x REDIS_URL="redis://redis:6379/"
declare -x SHLVL="1"
declare -x VIRTUAL_HOST="people"
```

**Comment by FedeG** [comment]
@andreareginato I try with `gem 'uglifier', '>= 1.0.3', require: 'uglifier'` but return the same error

**Comment by andreareginato** [comment]
Any possible idea to fix this @FedeG?

**Comment by FedeG** [comment]
@andreareginato 
i don't know any idea.
